from typing import AsyncIterator, Protocol


class ProviderError(RuntimeError):
    pass


class Provider(Protocol):
    input_rate: int
    output_rate: int

    async def open(self, instructions: str, tools: list[dict]) -> None: ...
    async def send_audio(self, pcm: bytes) -> None: ...
    def events(self) -> AsyncIterator[dict]: ...
    async def start_response(self) -> None: ...
    async def truncate_audio(self, item_id: str, content_index: int, audio_end_ms: int) -> None: ...
    async def update_context(self, text: str) -> None: ...
    async def tool_result(self, call_id: str, result: dict) -> None: ...
    async def close(self) -> None: ...
